platform :ios, '12.0'

flutter_application_path = File.expand_path('..', __FILE__)
load File.join(flutter_application_path, 'Flutter', 'podhelper.rb')

# Убедитесь, что этот путь правильный
flutter_export_environment_path = File.join(flutter_application_path, 'Flutter', 'flutter_export_environment.sh')

# Загрузите переменные окружения (если нужно)
if File.exist?(flutter_export_environment_path)
  puts "Flutter export environment file exists at: #{flutter_export_environment_path}"
  eval(File.read(flutter_export_environment_path)) # Вызываем eval для правильного экспорта переменных
else
  puts "Flutter export environment file does not exist at: #{flutter_export_environment_path}"
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Добавьте зависимости здесь
  pod 'Firebase', '~> 10.0'

  # Убедитесь, что вы вызываете правильную функцию
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
