platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Добавьте зависимости здесь
  pod 'Firebase', '~> 10.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
