platform :ios, '12.0'

require File.expand_path('../.flutter-plugins-dependencies', __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Добавьте зависимости здесь
  pod 'Firebase', '~> 10.0'

  flutter_application_path = File.expand_path('..', __FILE__)
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
